 #DHCPRelay - DHCP Relay between host network and PiHole bridge
  dhcprelay:
    #image: modem7/hda:dhcprelay
    image: modem7/hda:dhcprelayalpine
    restart: always
    network_mode: host
    container_name: DHCPRelay
    command: ["-id", "eno1", "-iu", "br_pihole", "10.0.0.3"] #https://fedoramagazine.org/build-network-bridge-fedora/
    cap_add:
      - NET_ADMIN
    mem_limit: 20m
    mem_reservation: 5m
